In [1]:
#1. 广播法则(rule)
#广播法则能使通用函数有意义地处理不具有相同形状的输入。
#广播第一法则：如果所有的输入数组维度不都相同，一个“1”将被重复地添加在维度较小的数组上直至所有的数组拥有一样的维度。
#广播第二法则：确定长度为1的数组沿着特殊的方向表现地好像它有沿着那个方向最大形状的大小。对数组来说，沿着那个维度的数组元素的值理应相同。
#应用广播法则之后，所有数组的大小必须匹配。

#2. 花哨的索引和索引技巧
#Numpy比普通Python序列提供更多的索引功能。除了索引整数和切片，正如我们之前看到的，数组可以被整数数组和布尔数组索引。

#通过数组索引
from numpy import *
a = arange(12)**2            # the first 12 square numbers
i = array([1,1,3,8,5])       # an array of indices
a[i]                         # the elements of a at the positions i

array([ 1,  1,  9, 64, 25], dtype=int32)

In [2]:
j = array([[3,4],[9,7]])      # a bidimensional array of indices
a[j]                          # the same shape as j

array([[ 9, 16],
       [81, 49]], dtype=int32)

In [3]:
#当被索引数组a是多维的时，每一个唯一的索引数列指向a的第一维5。以下示例通过将图片标签用调色版转换成色彩图像展示了这种行为。
palette = array([[0,0,0],        # 黑色
                 [255,0,0],      # 红色
                 [0,255,0],      # 绿色
                 [0,0,255],      # 蓝色
                 [255,255,255]]) # 白色
image = array([[0,1,2,0],        # each value corresponds to a color in the palette
               [0,3,4,0]])
palette[image]                  # the (2,4,3) color image

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [4]:
#我们也可以给出不不止一维的索引，每一维的索引数组必须有相同的形状。
a = arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
i = array([[0,1],   # indices for the first dim of a
           [1,2]])

In [6]:
j = array([[2,1],  # indices for the second dim
           [3,3]])

In [7]:
a[i,j]    # i and j must have equal shape

array([[ 2,  5],
       [ 7, 11]])

In [8]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [9]:
a[:,j]    # i.e., a[ : , j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [10]:
#自然，我们可以把i和j放到序列中(比如说列表)然后通过list索引。
l = [i,j]
a[l]         # 与 a[i,j] 相等

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  This is separate from the ipykernel package so we can avoid doing imports until


array([[ 2,  5],
       [ 7, 11]])

In [11]:
#另一个常用的数组索引用法是搜索时间序列最大值6。
time = linspace(20,145,5)                 # time scale
data = sin(arange(20)).reshape(5,4)       # 4 time-dependent series
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [12]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [13]:
ind = data.argmax(axis=0)    # index of the maxima for each series
ind

array([2, 0, 3, 1], dtype=int64)

In [14]:
time_max = time[ind]                       # times corresponding to the maxima
data_max = data[ind,range(data.shape[1])]  # => data[ind[0],0], data[ind[1],1]...
time_max

array([ 82.5 ,  20.  , 113.75,  51.25])

In [15]:
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [16]:
all(data_max == data.max(axis=0))

True

In [17]:
#你也可以使用数组索引作为目标来赋值：
a = arange(5)
a

array([0, 1, 2, 3, 4])

In [18]:
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

In [19]:
#然而，当一个索引列表包含重复时，赋值被多次完成，保留最后的值：
a = arange(5)
a[[0,0,2]] = [1,2,3]
a

array([2, 1, 3, 3, 4])

In [20]:
#这足够合理，但是小心如果你想用Python的+=结构，可能结果并非你所期望：
a = arange(5)
a[[0,0,2]] += 1
a
#即使0在索引列表中出现两次，索引为0的元素仅仅增加一次。这是因为Python要求a+=1和a=a+1等同。

array([1, 1, 3, 3, 4])

In [ ]:
#通过布尔数组索引
#当我们使用整数数组索引数组时，我们提供一个索引列表去选择。通过布尔数组索引的方法是不同的我们显式地选择数组中我们想要和不想要的元素。
#我们能想到的使用布尔数组的索引最自然方式就是使用和原数组一样形状的布尔数组。
