In [1]:
#导入Numpy库并简写为np
import numpy as np

In [3]:
#打印Numpy的版本和配置说明
print(np.__version__)

1.16.5


In [4]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda3\\Library\\include']
blas_op

In [5]:
#创建一个长度为10的空向量
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#如何找到任何一个数组的内存大小
data = np.zeros((10,10))
data

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
 print("%d bytes"%(data.size*data.itemsize))

800 bytes


In [8]:
#如何从命令行得到Numpy中add函数的说明文档
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [9]:
#创建一个长度为10并且除了第五个值为1的空向量
data = np.zeros(10)
data[4] = 1
print(data)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
#创建一个值域范围从10到49的向量
data = np.arange(10,50)
print(data)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
#反转一个向量
a = np.array([1,2,3,4,5,6])
b = a[::-1]
print(b)

[6 5 4 3 2 1]


In [12]:
#创建一个3*3并且值从0到8的矩阵
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#找到数组[1，2，0，0，4，0]中非0元素的位置索引
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int64),)

In [14]:
#创建一个3*3的单位矩阵
data = np.eye(3)
data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#创建一个3*3*3的随机数组
data = np.random.random((3,3,3))
data

array([[[0.23383651, 0.10799722, 0.02399378],
        [0.33549281, 0.84078579, 0.51972827],
        [0.9284153 , 0.63664638, 0.16289428]],

       [[0.62286767, 0.84026283, 0.30348376],
        [0.53787215, 0.94324681, 0.37668663],
        [0.4556853 , 0.76436018, 0.62335582]],

       [[0.78089836, 0.32195731, 0.52967258],
        [0.45618314, 0.82460866, 0.40969143],
        [0.49920557, 0.2682597 , 0.2553398 ]]])

In [16]:
#创建一个10*10的随机数组并找到他的最大值和最小值
data = np.random.random((10,10))
print(data)
datamin,datamax = data.min(),data.max()
print(datamin,datamax)

[[0.61061991 0.43061997 0.94448061 0.37530566 0.08939037 0.01772272
  0.10113274 0.09960076 0.10254467 0.05085495]
 [0.5258647  0.39120363 0.76087852 0.8255672  0.49200878 0.53301896
  0.04484105 0.7943735  0.97051246 0.02678924]
 [0.718087   0.85225193 0.53699582 0.47299091 0.00333951 0.05076847
  0.9280505  0.52530794 0.57532041 0.43436983]
 [0.61526103 0.9660548  0.58191328 0.90942694 0.22335036 0.24471451
  0.13844439 0.02347888 0.73342158 0.13155305]
 [0.00992654 0.38522013 0.31766642 0.72759462 0.7249528  0.59142913
  0.91897453 0.61267294 0.57954973 0.0612617 ]
 [0.24306655 0.76267227 0.28337692 0.02906144 0.71267463 0.49967628
  0.11433236 0.74405451 0.88697393 0.51143833]
 [0.22828382 0.35043498 0.617249   0.80778536 0.73416701 0.07621036
  0.38149044 0.79679656 0.80883678 0.58837188]
 [0.50800736 0.9566656  0.90328938 0.58364147 0.08468897 0.20314941
  0.22232429 0.736568   0.72444282 0.70782049]
 [0.5379317  0.81717834 0.42301525 0.14699739 0.91956361 0.3852844
  0.9500631  

In [17]:
#创建一个长度为30的随机向量并找到他的平均值
data = np.random.random(30)
print(data)
m = data.mean()
print(m)

[0.34514911 0.29583625 0.62419867 0.18372225 0.35446635 0.95947108
 0.38556611 0.0337543  0.753501   0.92392592 0.39468717 0.56477986
 0.2028411  0.6057377  0.76364788 0.50867409 0.26122137 0.6598473
 0.87475237 0.1333671  0.88749517 0.60518698 0.83376954 0.0539304
 0.66896939 0.46735221 0.34703718 0.52539828 0.5162611  0.40945537]
0.5048000873588914


In [18]:
#创建一个二维数组，其中边界值为1，其余值为0
data = np.ones((10,10))
data[1:-1,1:-1] = 0
print(data)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [19]:
#对于一个存在数组，如何添加一个用0填充的边界
data = np.ones((5,5))
data = np.pad(data,pad_width=1,mode='constant',constant_values=0)
print(data)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [20]:
#以下表达式运行的结果分别是什么
print(0 * np.nan)

nan


In [21]:
print(np.nan == np.nan)

False


In [22]:
print(np.inf > np.nan)

False


In [23]:
print(np.nan - np.nan)

nan


In [24]:
print(0.3 == 3 * 0.1)

False


In [25]:
#创建一个5*5的矩阵，并设置值1，2，3，4落在对角线下方位置
a = np.diag(np.arange(1,5),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [26]:
#创建一个8*8的矩阵，并且设置成棋盘样式
data = np.zeros((8,8),dtype=int)
data[1::2,::2] = 1
data[::2,1::2] = 1
print(data)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
#考虑一个(6,7,8)形状的数组，其第100个元素的索引(x,y,z)是什么
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [28]:
#用tile函数去创建一个8*8的棋盘样式矩阵
data = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(data)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [30]:
#对一个5*5的随机矩阵做归一化
data = np.random.random((5,5))
datamax,datamin = data.max(),data.min()
data = (data-datamin)/(datamax-datamin)
print(data)

[[0.33710206 0.25398976 0.28103766 0.41017971 0.58720724]
 [0.45142026 0.48385884 0.18747456 0.46119969 0.48178248]
 [0.10767304 1.         0.39819988 0.14272088 0.59759889]
 [0.88130955 0.92959623 0.27402478 0.34751436 0.        ]
 [0.77369093 0.05152328 0.10138122 0.91861432 0.2266445 ]]


In [31]:
#创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？
color = np.dtype([("r",np.ubyte,1),
                 ("g",np.ubyte,1),
                 ("b",np.ubyte,1),
                 ("a",np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [32]:
#一个5*3的矩阵与一个3*2的矩阵相乘，实矩阵乘积是什么？
data = np.dot(np.ones((5,3)),np.ones((3,2)))
data

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [33]:
#给定一个一维数组，对其在3到8之间的所有元素取反
data = np.arange(10)
data[(3<data)&(data<=8)]*=-1
print(data)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


In [34]:
#下面脚本运行后的结果是什么？
print(sum(range(5),-1))

9


In [35]:
from numpy import *
print(sum(range(5),-1))

10


In [36]:
#考虑一个整数向量Z，下列表达合法的是哪个？
z = np.arange(5)
z**z

array([  1,   1,   4,  27, 256], dtype=int32)

In [37]:
z = np.arange(5)
2<<z>>2

array([0, 1, 2, 4, 8], dtype=int32)

In [38]:
z = np.arange(5)
z<-z

array([False, False, False, False, False])

In [39]:
z = np.arange(5)
1j*z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [40]:
z = np.arange(5)
z/1/1

array([0., 1., 2., 3., 4.])

In [43]:
#下列表达式的结果分别是什么？
np.array(0)/np.array(0)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


nan

In [44]:
np.array(0)//np.array(0)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [45]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [48]:
#如何从零位对浮点数组做舍入？
data = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(data)),data))

[  4.  -7.   5. -10.  10.  10.  -1.   1.  -1.  -3.]


In [49]:
#如何找到两个数组中的共同元素？
data1 = np.random.randint(0,10,10)
data2 = np.random.randint(0,10,10)
print(np.intersect1d(data1,data2))

[1 3 6 7 9]


In [50]:
#如何忽略所有的numpy警告(尽管不建议这么做)？
defults = np.seterr(all="ignore")
data = np.ones(1)/0

In [51]:
#下面的表达式是正确的吗？
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [52]:
#如何得到昨天，今天，明天的日期？
yesterday = np.datetime64("today","D")-np.datetime64(1,"D")
yesterday

numpy.timedelta64(19769,'D')

In [53]:
today = np.datetime64("today","D")
today

numpy.datetime64('2024-02-17')

In [55]:
tomorrow = np.datetime64("today","D")+np.timedelta64(1,"D")
tomorrow

numpy.datetime64('2024-02-18')

In [56]:
#如何得到所有与2016年7月对应的日期？
data = np.arange("2016-07","2016-08",dtype="datetime64[D]")
data

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [57]:
#如何直接在位计算(A+B)*(-A/2)(不建立副本)？
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [58]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [60]:
#用五种不同的方法去提取一个随机数组的整数部分
data1 = np.random.uniform(0,10,10)
print(data1-data1%1)

[5. 6. 1. 2. 1. 9. 0. 4. 2. 6.]


In [61]:
np.floor(data1)

array([5., 6., 1., 2., 1., 9., 0., 4., 2., 6.])

In [62]:
np.ceil((data1)-1)

array([ 5.,  6.,  1.,  2.,  1.,  9., -0.,  4.,  2.,  6.])

In [63]:
data1.astype(int)

array([5, 6, 1, 2, 1, 9, 0, 4, 2, 6])

In [64]:
np.trunc(data1)

array([5., 6., 1., 2., 1., 9., 0., 4., 2., 6.])

In [65]:
#创建一个5*5的矩阵，其中每行的数值范围从0到4
data = np.zeros((5,5))
data += np.arange(5)
print(data)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [66]:
#通过考虑一个可生成10个整数的函数，来构建一个数组
def genter():
    for x in range(10):
        yield x
data = np.fromiter(genter(),dtype=float,count=-1)
print(data)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [67]:
#创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1
data = np.linspace(0,1,11,endpoint=False)[1:]
data

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [68]:
#创建一个长度为10的随机向量，并将其排序
data = np.random.random(10)
data.sort()
data

array([0.04097179, 0.06187073, 0.1002216 , 0.22026628, 0.2729469 ,
       0.29583529, 0.63728294, 0.70703438, 0.91112543, 0.98950066])

In [69]:
#对于一个小数组，如何用比np.sum更快的方式对其求和？
data = np.arange(10)
np.add.reduce(data)

45

In [70]:
#对于两个随机数组A和B，检查他们是否相等
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [71]:
data1 = np.array_equal(A,B)
data1

False

In [73]:
#创建一个只读数组(read-only)
z = np.zeros(10)
z.flags.writeable = False
#z[0] = 1

In [74]:
#将笛卡尔坐标下的一个10*2的矩阵转换为极坐标形式
data = np.random.random((10,2))
X,Y = data[:,0],data[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)

[1.19269656 0.51695959 0.47727986 0.66246769 0.28939142 0.20874633
 0.76460401 1.16693016 1.15623722 0.4263053 ]


In [75]:
print(T)

[0.5880862  0.24229842 0.69617713 1.45260369 0.1897875  0.80913872
 0.82491812 0.67694773 0.85050321 0.67922102]


In [77]:
#创建一个长度为10的向量，并将向量中最大值替换为1
data = np.random.random(10)
data[data.argmax()]=1
print(data)

[1.         0.18711632 0.81777362 0.02854654 0.1913595  0.74430849
 0.23361688 0.65850971 0.9310438  0.85569676]


In [78]:
#创建一个结构化数组，并实现x和y坐标覆盖[0,1]x[0,1]区域
data = np.ones((5,5),[("x",float),("y",float)])
data["x"],data["y"] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(data)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [79]:
#给定两个数组X和Y，构造Cauchy矩阵C(Cij = 1/(xi-yi))
X = np.arange(8)
Y = X+0.5
C = 1.0/np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.1636371179666


In [80]:
#打印每个numpy标量类型的最小值和最大值？
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [81]:
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


In [82]:
#如何打印一个数组中的所有数值？
import sys
np.set_printoptions(threshold=sys.maxsize)
z = np.zeros((16,16))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [83]:
#给定标量时，如何找到数组中最接近标量的值？
data = np.arange(100)
da = np.random.uniform(0,100)
index = (np.abs(data-da)).argmin()
print(data[index])

79


In [84]:
#创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组
data = np.zeros(10,[("position",[("x",float,1),
                                ("y",float,1)]),
                   ("color",[("r",float,1),
                            ("g",float,1),
                            ("b",float,1)])])
print(data)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]
