In [1]:
#导入Numpy库并简写为np
import numpy as np

In [3]:
#打印Numpy的版本和配置说明
print(np.__version__)

1.16.5


In [4]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda3\\Library\\include']
blas_op

In [5]:
#创建一个长度为10的空向量
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#如何找到任何一个数组的内存大小
data = np.zeros((10,10))
data

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
 print("%d bytes"%(data.size*data.itemsize))

800 bytes


In [8]:
#如何从命令行得到Numpy中add函数的说明文档
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [9]:
#创建一个长度为10并且除了第五个值为1的空向量
data = np.zeros(10)
data[4] = 1
print(data)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
#创建一个值域范围从10到49的向量
data = np.arange(10,50)
print(data)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
#反转一个向量
a = np.array([1,2,3,4,5,6])
b = a[::-1]
print(b)

[6 5 4 3 2 1]


In [12]:
#创建一个3*3并且值从0到8的矩阵
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#找到数组[1，2，0，0，4，0]中非0元素的位置索引
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int64),)

In [14]:
#创建一个3*3的单位矩阵
data = np.eye(3)
data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#创建一个3*3*3的随机数组
data = np.random.random((3,3,3))
data

array([[[0.23383651, 0.10799722, 0.02399378],
        [0.33549281, 0.84078579, 0.51972827],
        [0.9284153 , 0.63664638, 0.16289428]],

       [[0.62286767, 0.84026283, 0.30348376],
        [0.53787215, 0.94324681, 0.37668663],
        [0.4556853 , 0.76436018, 0.62335582]],

       [[0.78089836, 0.32195731, 0.52967258],
        [0.45618314, 0.82460866, 0.40969143],
        [0.49920557, 0.2682597 , 0.2553398 ]]])

In [16]:
#创建一个10*10的随机数组并找到他的最大值和最小值
data = np.random.random((10,10))
print(data)
datamin,datamax = data.min(),data.max()
print(datamin,datamax)

[[0.61061991 0.43061997 0.94448061 0.37530566 0.08939037 0.01772272
  0.10113274 0.09960076 0.10254467 0.05085495]
 [0.5258647  0.39120363 0.76087852 0.8255672  0.49200878 0.53301896
  0.04484105 0.7943735  0.97051246 0.02678924]
 [0.718087   0.85225193 0.53699582 0.47299091 0.00333951 0.05076847
  0.9280505  0.52530794 0.57532041 0.43436983]
 [0.61526103 0.9660548  0.58191328 0.90942694 0.22335036 0.24471451
  0.13844439 0.02347888 0.73342158 0.13155305]
 [0.00992654 0.38522013 0.31766642 0.72759462 0.7249528  0.59142913
  0.91897453 0.61267294 0.57954973 0.0612617 ]
 [0.24306655 0.76267227 0.28337692 0.02906144 0.71267463 0.49967628
  0.11433236 0.74405451 0.88697393 0.51143833]
 [0.22828382 0.35043498 0.617249   0.80778536 0.73416701 0.07621036
  0.38149044 0.79679656 0.80883678 0.58837188]
 [0.50800736 0.9566656  0.90328938 0.58364147 0.08468897 0.20314941
  0.22232429 0.736568   0.72444282 0.70782049]
 [0.5379317  0.81717834 0.42301525 0.14699739 0.91956361 0.3852844
  0.9500631  

In [17]:
#创建一个长度为30的随机向量并找到他的平均值
data = np.random.random(30)
print(data)
m = data.mean()
print(m)

[0.34514911 0.29583625 0.62419867 0.18372225 0.35446635 0.95947108
 0.38556611 0.0337543  0.753501   0.92392592 0.39468717 0.56477986
 0.2028411  0.6057377  0.76364788 0.50867409 0.26122137 0.6598473
 0.87475237 0.1333671  0.88749517 0.60518698 0.83376954 0.0539304
 0.66896939 0.46735221 0.34703718 0.52539828 0.5162611  0.40945537]
0.5048000873588914


In [18]:
#创建一个二维数组，其中边界值为1，其余值为0
data = np.ones((10,10))
data[1:-1,1:-1] = 0
print(data)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [19]:
#对于一个存在数组，如何添加一个用0填充的边界
data = np.ones((5,5))
data = np.pad(data,pad_width=1,mode='constant',constant_values=0)
print(data)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [20]:
#以下表达式运行的结果分别是什么
print(0 * np.nan)

nan


In [21]:
print(np.nan == np.nan)

False


In [22]:
print(np.inf > np.nan)

False


In [23]:
print(np.nan - np.nan)

nan


In [24]:
print(0.3 == 3 * 0.1)

False


In [25]:
#创建一个5*5的矩阵，并设置值1，2，3，4落在对角线下方位置
a = np.diag(np.arange(1,5),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [26]:
#创建一个8*8的矩阵，并且设置成棋盘样式
data = np.zeros((8,8),dtype=int)
data[1::2,::2] = 1
data[::2,1::2] = 1
print(data)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
#考虑一个(6,7,8)形状的数组，其第100个元素的索引(x,y,z)是什么
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [28]:
#用tile函数去创建一个8*8的棋盘样式矩阵
data = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(data)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [30]:
#对一个5*5的随机矩阵做归一化
data = np.random.random((5,5))
datamax,datamin = data.max(),data.min()
data = (data-datamin)/(datamax-datamin)
print(data)

[[0.33710206 0.25398976 0.28103766 0.41017971 0.58720724]
 [0.45142026 0.48385884 0.18747456 0.46119969 0.48178248]
 [0.10767304 1.         0.39819988 0.14272088 0.59759889]
 [0.88130955 0.92959623 0.27402478 0.34751436 0.        ]
 [0.77369093 0.05152328 0.10138122 0.91861432 0.2266445 ]]


In [31]:
#创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？
color = np.dtype([("r",np.ubyte,1),
                 ("g",np.ubyte,1),
                 ("b",np.ubyte,1),
                 ("a",np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [32]:
#一个5*3的矩阵与一个3*2的矩阵相乘，实矩阵乘积是什么？
data = np.dot(np.ones((5,3)),np.ones((3,2)))
data

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [33]:
#给定一个一维数组，对其在3到8之间的所有元素取反
data = np.arange(10)
data[(3<data)&(data<=8)]*=-1
print(data)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


In [34]:
#下面脚本运行后的结果是什么？
print(sum(range(5),-1))

9


In [35]:
from numpy import *
print(sum(range(5),-1))

10


In [36]:
#考虑一个整数向量Z，下列表达合法的是哪个？
z = np.arange(5)
z**z

array([  1,   1,   4,  27, 256], dtype=int32)

In [37]:
z = np.arange(5)
2<<z>>2

array([0, 1, 2, 4, 8], dtype=int32)

In [38]:
z = np.arange(5)
z<-z

array([False, False, False, False, False])

In [39]:
z = np.arange(5)
1j*z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [40]:
z = np.arange(5)
z/1/1

array([0., 1., 2., 3., 4.])

In [43]:
#下列表达式的结果分别是什么？
np.array(0)/np.array(0)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


nan

In [44]:
np.array(0)//np.array(0)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [45]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [48]:
#如何从零位对浮点数组做舍入？
data = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(data)),data))

[  4.  -7.   5. -10.  10.  10.  -1.   1.  -1.  -3.]


In [49]:
#如何找到两个数组中的共同元素？
data1 = np.random.randint(0,10,10)
data2 = np.random.randint(0,10,10)
print(np.intersect1d(data1,data2))

[1 3 6 7 9]


In [50]:
#如何忽略所有的numpy警告(尽管不建议这么做)？
defults = np.seterr(all="ignore")
data = np.ones(1)/0

In [51]:
#下面的表达式是正确的吗？
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [52]:
#如何得到昨天，今天，明天的日期？
yesterday = np.datetime64("today","D")-np.datetime64(1,"D")
yesterday

numpy.timedelta64(19769,'D')

In [53]:
today = np.datetime64("today","D")
today

numpy.datetime64('2024-02-17')

In [55]:
tomorrow = np.datetime64("today","D")+np.timedelta64(1,"D")
tomorrow

numpy.datetime64('2024-02-18')

In [56]:
#如何得到所有与2016年7月对应的日期？
data = np.arange("2016-07","2016-08",dtype="datetime64[D]")
data

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [57]:
#如何直接在位计算(A+B)*(-A/2)(不建立副本)？
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [58]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [60]:
#用五种不同的方法去提取一个随机数组的整数部分
data1 = np.random.uniform(0,10,10)
print(data1-data1%1)

[5. 6. 1. 2. 1. 9. 0. 4. 2. 6.]


In [61]:
np.floor(data1)

array([5., 6., 1., 2., 1., 9., 0., 4., 2., 6.])

In [62]:
np.ceil((data1)-1)

array([ 5.,  6.,  1.,  2.,  1.,  9., -0.,  4.,  2.,  6.])

In [63]:
data1.astype(int)

array([5, 6, 1, 2, 1, 9, 0, 4, 2, 6])

In [64]:
np.trunc(data1)

array([5., 6., 1., 2., 1., 9., 0., 4., 2., 6.])

In [65]:
#创建一个5*5的矩阵，其中每行的数值范围从0到4
data = np.zeros((5,5))
data += np.arange(5)
print(data)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [66]:
#通过考虑一个可生成10个整数的函数，来构建一个数组
def genter():
    for x in range(10):
        yield x
data = np.fromiter(genter(),dtype=float,count=-1)
print(data)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [67]:
#创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1
data = np.linspace(0,1,11,endpoint=False)[1:]
data

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [68]:
#创建一个长度为10的随机向量，并将其排序
data = np.random.random(10)
data.sort()
data

array([0.04097179, 0.06187073, 0.1002216 , 0.22026628, 0.2729469 ,
       0.29583529, 0.63728294, 0.70703438, 0.91112543, 0.98950066])

In [69]:
#对于一个小数组，如何用比np.sum更快的方式对其求和？
data = np.arange(10)
np.add.reduce(data)

45

In [70]:
#对于两个随机数组A和B，检查他们是否相等
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [71]:
data1 = np.array_equal(A,B)
data1

False

In [73]:
#创建一个只读数组(read-only)
z = np.zeros(10)
z.flags.writeable = False
#z[0] = 1

In [74]:
#将笛卡尔坐标下的一个10*2的矩阵转换为极坐标形式
data = np.random.random((10,2))
X,Y = data[:,0],data[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)

[1.19269656 0.51695959 0.47727986 0.66246769 0.28939142 0.20874633
 0.76460401 1.16693016 1.15623722 0.4263053 ]


In [75]:
print(T)

[0.5880862  0.24229842 0.69617713 1.45260369 0.1897875  0.80913872
 0.82491812 0.67694773 0.85050321 0.67922102]


In [77]:
#创建一个长度为10的向量，并将向量中最大值替换为1
data = np.random.random(10)
data[data.argmax()]=1
print(data)

[1.         0.18711632 0.81777362 0.02854654 0.1913595  0.74430849
 0.23361688 0.65850971 0.9310438  0.85569676]


In [78]:
#创建一个结构化数组，并实现x和y坐标覆盖[0,1]x[0,1]区域
data = np.ones((5,5),[("x",float),("y",float)])
data["x"],data["y"] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(data)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [79]:
#给定两个数组X和Y，构造Cauchy矩阵C(Cij = 1/(xi-yi))
X = np.arange(8)
Y = X+0.5
C = 1.0/np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.1636371179666


In [80]:
#打印每个numpy标量类型的最小值和最大值？
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [81]:
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


In [82]:
#如何打印一个数组中的所有数值？
import sys
np.set_printoptions(threshold=sys.maxsize)
z = np.zeros((16,16))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [83]:
#给定标量时，如何找到数组中最接近标量的值？
data = np.arange(100)
da = np.random.uniform(0,100)
index = (np.abs(data-da)).argmin()
print(data[index])

79


In [84]:
#创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组
data = np.zeros(10,[("position",[("x",float,1),
                                ("y",float,1)]),
                   ("color",[("r",float,1),
                            ("g",float,1),
                            ("b",float,1)])])
print(data)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [7]:
import numpy as np
#对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离
data = np.random.random((10,2))
X,Y = np.atleast_2d(data[:,0],data[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.56079413 0.34052081 0.43975263 0.34630328 0.48236082
  0.69089703 0.32304247 0.30935871 0.16013677]
 [0.56079413 0.         0.24382363 0.20671992 0.76276485 0.68451025
  0.29886047 0.61151556 0.80767352 0.70781526]
 [0.34052081 0.24382363 0.         0.10640068 0.52056753 0.47440674
  0.4754932  0.37679861 0.62475851 0.47430376]
 [0.43975263 0.20671992 0.10640068 0.         0.57321961 0.47782169
  0.48631449 0.41323808 0.73004797 0.56316727]
 [0.34630328 0.76276485 0.52056753 0.57321961 0.         0.25534773
  0.97403024 0.17144393 0.5485129  0.24947227]
 [0.48236082 0.68451025 0.47440674 0.47782169 0.25534773 0.
  0.94895874 0.15954601 0.75506359 0.45874316]
 [0.69089703 0.29886047 0.4754932  0.48631449 0.97403024 0.94895874
  0.         0.84763538 0.84515231 0.85099258]
 [0.32304247 0.61151556 0.37679861 0.41323808 0.17144393 0.15954601
  0.84763538 0.         0.59949318 0.30955645]
 [0.30935871 0.80767352 0.62475851 0.73004797 0.5485129  0.75506359
  0.84515231 0.59949

In [8]:
#如何将32位的浮点数(float)转换为对应的整数(integer)?
data = np.arange(10,dtype=np.int32)
data = data.astype(np.float32,copy=False)
print(data)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [10]:
#对于numpy数组，enumerate的等价操作是什么？
data = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(data):
    print(index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [11]:
#生成一个通用的二维Gaussian-like数组
X,Y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2/(2.0*sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [13]:
#对于一个二维数组，如何在其内部随机放置p个元素？
n = 10
p = 5
data = np.zeros((n,n))
np.put(data,np.random.choice(range(n*n),p,replace=False),1)
print(data)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [14]:
#减去一个矩阵中的每一行的平均值
X = np.random.rand(5,10)
Y = X-X.mean(axis=1,keepdims=True)
print(Y)

[[ 0.0005321  -0.18012029 -0.12498044 -0.0208008  -0.28845544 -0.15203704
   0.09190318 -0.09368927  0.44678776  0.32086023]
 [ 0.52692111  0.40438811 -0.38925068  0.1652935   0.14724653  0.01322153
  -0.34951513 -0.17035731 -0.34218319 -0.00576446]
 [-0.16793749 -0.45315943  0.31413681  0.45647214 -0.02973205  0.3181338
   0.05763121 -0.22521602  0.18054321 -0.45087218]
 [ 0.01425966 -0.27864991 -0.16230952 -0.28289315  0.04025225  0.04997049
   0.03433256  0.15207491  0.22239113  0.21057159]
 [-0.21244492  0.02027802  0.00575431 -0.43330932  0.35291922  0.33254591
   0.28627327 -0.34890708  0.02756992 -0.03067934]]


In [15]:
#如何通过第n列对一个数组进行排序？
data = np.random.randint(0,10,(3,3))
print(data)

[[2 8 4]
 [8 4 3]
 [1 5 9]]


In [16]:
print(data[data[:1].argsort()])

[[[2 8 4]
  [1 5 9]
  [8 4 3]]]


In [18]:
#如何检查一个二维数组是否有空列？
data = np.random.randint(0,3,(3,10))
print((data.any(axis=0)).any())

True


In [19]:
#从数组中的给定值中找出最近的值
daat = np.random.uniform(0,1,10)
data1 = 0.5
m = data.flat[np.abs(data-data1).argmin()]
print(m)

1


In [20]:
#如何用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组？
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
data = np.nditer([A,B,None])
for x,y,z in data:
    z[...] = x+y
print(data.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [21]:
#创建一个具有name属性的数组类
class NamedArray(np.ndarray):
    def __new__(cls,array,name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self,obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
        
Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


In [22]:
#考虑一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)？
data = np.ones(10)
data1 = np.random.randint(0,len(data),20)
data += np.bincount(data1,minlength=len(data))
print(data)

[2. 2. 4. 2. 5. 4. 2. 2. 4. 3.]


In [23]:
data = np.ones(10)
data1 = np.random.randint(0,len(data),20)
data += np.bincount(data1,minlength=len(data))
print(data)

[2. 2. 6. 3. 3. 1. 3. 2. 3. 5.]


In [24]:
data = np.ones(10)
data1 = np.random.randint(0,len(data),20)
A = np.add.at(data,data1,1)
print(A)

None


In [25]:
#根据索引列表(I),如何将向量(X)的元素累加到数组(F)?
x = [1,2,3,4,5,6]
y = [1,3,9,3,4,1]
F = np.bincount(x,y)
print(F)

[0. 1. 3. 9. 3. 4. 1.]


In [26]:
#考虑一个(dtype=ubyte)的(w,h,3)图像，计算其唯一颜色的数量
w,h = 16,16
data = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = data[...,0]*(256*256) + data[...,1]*256 + data[...,2]
n = len(np.unique(F))
print(n)

8


In [27]:
#考虑一个四维数组，如何一次性计算出最后两个轴(axis)的和？
data = np.random.randint(0,10,(3,4,3,4))
sum = data.sum(axis=(-2,-1))
sum

array([[59, 58, 74, 48],
       [57, 51, 41, 43],
       [73, 49, 51, 52]])

In [28]:
#考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sum = np.bincount(S,weights=D)
D_counts = np.bincount(S)
D_means = D_sum/D_counts
print(D_means)

[0.37690144 0.59324959 0.66854532 0.56181233 0.46127023 0.54621294
 0.55699403 0.44030644 0.33428458 0.40782186]


In [29]:
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.376901
1    0.593250
2    0.668545
3    0.561812
4    0.461270
5    0.546213
6    0.556994
7    0.440306
8    0.334285
9    0.407822
dtype: float64


In [30]:
#如何获得点积dot product的对角线？
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A,B))

array([1.05354178, 0.63894041, 0.96625707, 1.15191079, 2.35214803])

In [31]:
np.sum(A*B.T,axis=1)

array([1.05354178, 0.63894041, 0.96625707, 1.15191079, 2.35214803])

In [32]:
#考虑一个向量[1，2，3，4，5]，如何建立一个新的向量，在这个新向量中每个值之间有3个连续的零？
data = np.array([1,2,3,4,5])
nz = 3
data1 = np.zeros(len(data)+(len(data)-1)*nz)
data1[::nz+1] = data
print(data1)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [33]:
#考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A*B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [34]:
#如何对一个数组中任意两行做交换？
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [35]:
#考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的linesegment
face = np.random.randint(0,100,(10,3))
F = np.roll(face.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view(dtype=[("p0",F.dtype),("p1",F.dtype)])
G = np.unique(G)
print(G)

[( 3, 28) ( 3, 38) ( 7, 31) ( 7, 79) ( 8, 40) ( 8, 83) (15, 47) (15, 63)
 (26, 41) (26, 83) (27, 43) (27, 78) (28, 38) (31, 79) (37, 55) (37, 90)
 (40, 83) (41, 83) (43, 67) (43, 73) (43, 78) (45, 69) (45, 86) (47, 63)
 (55, 90) (63, 75) (63, 78) (67, 73) (69, 86) (75, 78)]


In [36]:
#给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)==C
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)),C)
print(C)

[0 2 1 1 2 0 1]


In [37]:
#如何通过滑动窗口计算一个数组的平均数？
def moving_average(a,n=3):
    ret = np.cumsum(a,dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:]/n
Z = np.arange(20)
print(moving_average(Z,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [38]:
#如何对布尔值取反，或者原位(in-place)改变浮点数的符号(sign)?
data = np.random.randint(0,2,100)
np.logical_not(data,out=data)

array([0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0])

In [39]:
data = np.random.uniform(-1.0,1.0,100)
np.negative(data,out=data)

array([ 4.32968317e-01, -4.42288868e-01,  1.78464370e-01, -7.49431193e-01,
       -8.63836586e-01,  5.91863947e-01, -8.24854968e-01, -3.77740132e-01,
        8.01565540e-01, -7.19260311e-01,  8.42587488e-01, -4.07697512e-01,
       -5.30906039e-01,  8.20971099e-01,  1.18225961e-01,  2.71289829e-03,
        7.03267329e-01, -4.46617823e-01,  1.18708299e-01, -7.74265862e-01,
        1.02930320e-01,  3.36009653e-01,  1.67322370e-01, -5.54206393e-01,
       -2.28127430e-01, -6.18254338e-01,  8.06287355e-01,  5.14208221e-01,
        5.64968282e-01, -8.05649607e-02, -1.60110451e-01,  7.15945500e-01,
        4.64253149e-02, -6.42396692e-01, -3.50747883e-01,  5.05360711e-01,
       -9.48533126e-01,  7.64678148e-01,  9.26942758e-01, -6.55997216e-01,
        2.18589728e-01,  1.95937755e-01, -9.16135328e-01,  7.68712265e-01,
        2.76468292e-02, -3.99496028e-01, -8.59237828e-01, -3.37793086e-04,
       -3.51201621e-01,  6.01863644e-01,  6.35077998e-01,  9.47668251e-01,
       -7.03056911e-02, -

In [40]:
#考虑两组点集P0和P1去描述一组线(二维)和一个点p，如何计算点p到每一条线i(P0[i],P1[i])的距离？
def distance(P0,P1,p):
    T = P1-P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0]*T[:,0] + (P0[:,1]-p[...,1])*T[:,1])/L)
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(1,2))
print(distance(P0,P1,p))

[ 9.07781328  1.99740409  6.58318502  7.22172507  8.83756586  5.33547565
  6.45161674  9.64500859 12.3357261   5.8893993 ]


In [41]:
#考虑两组点集P0和P1去描述一组线(二维)和一组点集P，如何计算每一个点j(P[j])到每一条线i(P0[i],P1[i])的距离？
p0 = np.random.uniform(-10,10,(10,2))
p1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(10,2))
print(np.array([distance(p0,p1,p_i) for p_i in p]))

[[13.55455477 14.05133346  6.30151657 10.6197723   3.20305696 13.75289344
   0.47321882  4.17440106 14.2866549   6.72232968]
 [12.618688    4.05440745 15.90921033 15.78780435 12.92003124  4.25662457
  14.10038208 11.61838885  1.82632756  8.96622734]
 [ 8.66617823  5.18672162  3.99412973  9.34767715  4.44029526  1.94935856
   7.44813038  6.20220765 10.21086442 10.52928138]
 [ 9.04948741  6.12761736  6.20138576  9.00798145  3.45293743  4.4701103
  16.28879309  4.37691786  1.71468603 16.20097817]
 [ 8.63901236  5.3615503  10.23443417 10.73280285  7.32697934  2.04723542
  16.50549538  7.36583771  1.62814258 14.00614924]
 [13.3228998   5.59189833 14.12229795 14.9401088  11.03041687  6.87902237
  10.63383661  9.3295944   2.61269769  7.16988546]
 [ 8.53174858  4.04988934  5.88045476  9.09020152  3.12939053  0.92787106
  12.48955777  3.90277711  4.40638974 12.67880248]
 [ 9.45132602 12.946908    4.45513864  9.11785344  5.78787072 10.42399803
   1.24400344  8.98526546 17.52952078  5.94637798]
 