In [1]:
from numpy import *
a = arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype.name

'int32'

In [5]:
a.itemsize

4

In [6]:
a.size

15

In [7]:
type(a)

numpy.ndarray

In [8]:
b = array([6,7,8])
b

array([6, 7, 8])

In [9]:
type(b)

numpy.ndarray

In [10]:
a = array([2,3,4])
a

array([2, 3, 4])

In [11]:
a.dtype

dtype('int32')

In [12]:
b = array([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [13]:
#数组将序列包含序列转化成二维的数组，序列包含序列包含序列转化成三维数组等等。
b = array([(1.5,2,3),(4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [14]:
#数组类型可以在创建时显示指定
c = array([[1,2],[3,4]],dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [15]:
#通常，数组的元素开始都是未知的，但是它的大小已知。因此，Numpy提供了一些使用占位符创建数组的函数。
#这最小化了扩展数组的需要和高昂的运算代价。
#函数function创建一个全是0的数组，函数ones创建一个全1的数组，函数empty创建一个内容随机并且依赖与内存状态的数组。
#默认创建的数组类型(dtype)都是float64。
zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
ones((2,3,4),dtype=int16)# dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [17]:
empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
#为了创建一个数列，Numpy提供一个类似arange的函数返回数组而不是列表:
arange(10,30,5)

array([10, 15, 20, 25])

In [19]:
arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [20]:
#当arange使用浮点数参数时，由于有限的浮点数精度，通常无法预测获得的元素个数。
#因此，最好使用函数linspace去接收我们想要的元素个数来代替用range来指定步长。
#当你打印一个数组，NumPy以类似嵌套列表的形式显示它，但是呈以下布局：
#最后的轴从左到右打印
#次后的轴从顶向下打印
#剩下的轴从顶向下打印，每个切片通过一个空行与下一个隔开
#一维数组被打印成行，二维数组成矩阵，三维数组成矩阵列表。
a = arange(6) # 1d array
print(a)

[0 1 2 3 4 5]


In [21]:
b = arange(12).reshape(4,3) # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [22]:
c = arange(24).reshape(2,3,4) # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [23]:
#如果一个数组用来打印太大了，NumPy自动省略中间部分而只打印角落
print(arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [24]:
print(arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [25]:
#禁用NumPy的这种行为并强制打印整个数组，你可以设置printoptions参数来更改打印选项。
#set_printoptions(threshold='nan')
#数组的算术运算是按元素的。新的数组被创建并且被结果填充
a = array([20,30,40,50])
b = arange(4)
b

array([0, 1, 2, 3])

In [26]:
c = a-b
c

array([20, 29, 38, 47])

In [27]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [28]:
10*sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [29]:
a<35

array([ True,  True, False, False])

In [30]:
#不像许多矩阵语言，NumPy中的乘法运算符*指示按元素计算，矩阵乘法可以使用dot函数或创建矩阵对象实现
A = array([[1,1],
          [0,1]])
B = array([[2,0],
          [3,4]])
A*B  # elementwise product

array([[2, 0],
       [0, 4]])

In [31]:
dot(A,B)  # matrix product

array([[5, 4],
       [3, 4]])

In [32]:
#有些操作符像+=和*=被用来更改已存在数组而不创建一个新的数组。
a = ones((2,3),dtype=int)
b = random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [33]:
b += a
b

array([[3.66550199, 3.74635323, 3.44632462],
       [3.962733  , 3.56132818, 3.74137918]])

In [34]:
#当运算的是不同类型的数组时，结果数组和更普遍和精确的已知，这种行为叫做 upcast。
a = ones(3,dtype=int32)
b = linspace(0,pi,3)
b.dtype.name

'float64'

In [35]:
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [36]:
c.dtype.name

'float64'

In [37]:
d = exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [38]:
d.dtype.name# 许多非数组运算，如计算数组所有元素之和，被作为ndarray类的方法实现

'complex128'

In [39]:
a = random.random((2,3))
a

array([[0.24669845, 0.83823849, 0.17406082],
       [0.08253479, 0.56513111, 0.14184686]])

In [40]:
a.sum()

2.0485105187454464

In [41]:
a.min()

0.08253479002487052

In [42]:
a.max()

0.8382384862732704

In [43]:
#这些运算默认应用到数组好像它就是一个数字组成的列表，无关数组的形状。然而，指定axis参数你可以吧运算应用到数组指定的轴上：
b = arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
b.sum(axis=0)# sum of each column

array([12, 15, 18, 21])

In [45]:
b.min(axis=1)# min of each row

array([0, 4, 8])

In [46]:
b.cumsum(axis=1)# cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [47]:
#Numpy提供常见的数学函数如 sin, cos 和 exp。在Numpy中，这些叫作通用函数 ufunc。
#在Numpy里这些函数作用按数组的元素运算，产生一个数组作为输出。
B = arange(3)
B

array([0, 1, 2])

In [48]:
exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [49]:
sqrt(B)

array([0.        , 1.        , 1.41421356])

In [50]:
C = array([2.,-1.,4.])
add(B,C)

array([2., 0., 6.])

In [51]:
#一维数组可以被索引、切片和迭代，就像列表和其它Python序列。
a = arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [52]:
a[2]

8

In [53]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [54]:
a[:6:2] = -1000  # equivalent to a[0:6:2] = -1000; 
a                # from start to position 6, exclusive, set every 2nd element to -1000

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [55]:
a[::-1] # reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [56]:
for i in a:
    print(i**(1/3.),end=",")

nan,1.0,nan,3.0,nan,5.0,5.999999999999999,6.999999999999999,7.999999999999999,8.999999999999998,

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [57]:
#多维数组可以每个轴有一个索引。这些索引由一个逗号分割的元组给出。
def f(x,y):
    return 10*x+y
b = fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [58]:
b[2,3]

23

In [59]:
b[0:5,1]  # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [2]:
from numpy import *
def f(x,y):
    return 10*x+y
b = fromfunction(f,(5,4),dtype=int)

b[:,1]   # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [3]:
b[1:3,:]   # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [4]:
#当少于轴数的索引被提供时，确失的索引被认为是整个切片：
b[-1]  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

In [5]:
#b[i]中括号中的表达式被当作i和一系列:，来代表剩下的轴。NumPy也允许你使用“点”像b[i,...]。
#点(…)代表许多产生一个完整的索引元组必要的分号。如果x是秩为5的数组(即它有5个轴)，那么:
#x[1,2,…] 等同于 x[1,2,:,:,:]
#x[…,3] 等同于 x[:,:,:,:,3]
#x[4,…,5,:] 等同于 x[4,:,:,5,:]

# c = array( [ [[  0,  1,  2],  # a 3D array (two stacked 2D arrays) ... [ 10, 12, 13]]...   
# [[100,101,102], ... [110,112,113]] ] )   
# c.shape (2, 2, 3)   
# c[1,...]    # same as c[1,:,:] or c[1] array([[100, 101, 102], [110, 112, 113]])   
# c[...,2]      # same as c[:,:,2] array([[  2,  13], [102, 113]])

#迭代多维数组是就第一个轴而言的
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [7]:
#然而，如果一个人想对每个数组中元素进行运算，我们可以使用flat属性，该属性是数组元素的一个迭代器:
for element in b.flat:
    print(element,end=",")

0,1,2,3,10,11,12,13,20,21,22,23,30,31,32,33,40,41,42,43,

In [8]:
#一个数组的形状由它每个轴上的元素个数给出：
a = floor(10*random.random((3,4)))
a

array([[8., 0., 4., 0.],
       [4., 4., 0., 8.],
       [8., 5., 9., 5.]])

In [9]:
a.shape

(3, 4)

In [10]:
#一个数组的形状可以被多种命令修改：
a.ravel()  # flatten the array对数组进行扁平化处理

array([8., 0., 4., 0., 4., 4., 0., 8., 8., 5., 9., 5.])

In [11]:
a.shape = (6,2)
a.transpose()

array([[8., 4., 4., 0., 8., 9.],
       [0., 0., 4., 8., 5., 5.]])

In [12]:
#由ravel()展平的数组元素的顺序通常是 C风格 的，就是说，最右边的索引变化得最快，所以元素a[0,0]之后是a[0,1]。
#如果数组被改变形状(reshape)成其它形状，数组仍然是 C风格 的。Numpy通常创建一个以这个顺序保存数据的数组，
#所以ravel()将总是不需要复制它的参数。但是如果数组是通过切片其它数组或有不同寻常的选项时，它可能需要被复制。
#函数reshape()和ravel()还可以被同过一些可选参数构建成 FORTRAN风格 的数组，即最左边的索引变化最快。
#reshape函数改变参数形状并返回它，而resize函数改变数组自身。
a

array([[8., 0.],
       [4., 0.],
       [4., 4.],
       [0., 8.],
       [8., 5.],
       [9., 5.]])

In [13]:
a.resize((2,6))
a

array([[8., 0., 4., 0., 4., 4.],
       [0., 8., 8., 5., 9., 5.]])

In [14]:
#如果在改变形状操作中一个维度被给做-1，其维度将自动被计算
#几种方法可以沿不同轴将数组堆叠在一起：
a = floor(10*random.random((2,2)))
a

array([[7., 0.],
       [7., 1.]])

In [15]:
b = floor(10*random.random((2,2)))
b

array([[0., 4.],
       [8., 4.]])

In [16]:
vstack((a,b))

array([[7., 0.],
       [7., 1.],
       [0., 4.],
       [8., 4.]])

In [17]:
hstack((a,b))

array([[7., 0., 0., 4.],
       [7., 1., 8., 4.]])

In [18]:
#函数column_stack以列将一维数组合成二维数组，它等同与vstack对一维数组。
column_stack((a,b))  # With 2D arrays

array([[7., 0., 0., 4.],
       [7., 1., 8., 4.]])

In [19]:
a = array([4.,2.])
b = array([2.,8.])
a[:,newaxis]  # This allows to have a 2D columns vector

array([[4.],
       [2.]])

In [20]:
column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 2.],
       [2., 8.]])

In [21]:
vstack((a[:,newaxis],b[:,newaxis]))  # The behavior of vstack is different

array([[4.],
       [2.],
       [2.],
       [8.]])

In [22]:
#row_stack函数，另一方面，将一维数组以行组合成二维数组。
#对那些维度比二维更高的数组，hstack沿着第二个轴组合，vstack沿着第一个轴组合,concatenate允许可选参数给出组合时沿着的轴。
#在复杂情况下，r_[]和c_[]对创建沿着一个方向组合的数很有用，它们允许范围符号(“:”):
r_[1:4,0,4]
#当使用数组作为参数时，r_和c_的默认行为和vstack和hstack很像，但是允许可选的参数给出组合所沿着的轴的代号。

array([1, 2, 3, 0, 4])

In [23]:
#使用hsplit你能将数组沿着它的水平轴分割，或者指定返回相同形状数组的个数，或者指定在哪些列后发生分割:
a = floor(10*random.random((2,12)))
a

array([[3., 7., 2., 9., 8., 2., 6., 9., 8., 6., 5., 8.],
       [9., 2., 8., 7., 1., 4., 1., 5., 5., 5., 0., 7.]])

In [24]:
hsplit(a,3)  # Split a into 3

[array([[3., 7., 2., 9.],
        [9., 2., 8., 7.]]), array([[8., 2., 6., 9.],
        [1., 4., 1., 5.]]), array([[8., 6., 5., 8.],
        [5., 5., 0., 7.]])]

In [25]:
hsplit(a,(3,4))  # Split a after the third and the fourth column
#vsplit沿着纵向的轴分割，array split允许指定沿哪个轴分割。

[array([[3., 7., 2.],
        [9., 2., 8.]]), array([[9.],
        [7.]]), array([[8., 2., 6., 9., 8., 6., 5., 8.],
        [1., 4., 1., 5., 5., 5., 0., 7.]])]

In [26]:
#当运算和处理数组时，它们的数据有时被拷贝到新的数组有时不是。这通常是新手的困惑之源。这有三种情况:
#完全不拷贝
#简单的赋值不拷贝数组对象或它们的数据。
a = arange(12)
b = a         # no new object is created
b is a        # a and b are two names for the same ndarray object

True

In [27]:
b.shape = 3,4   # changes the shape of a
a.shape

(3, 4)

In [28]:
#Python 传递不定对象作为参考，所以函数调用不拷贝数组。
def f(x):
    print(id(x))

In [29]:
id(a)     # id is a unique identifier of an object

2438044102208

In [30]:
f(a)

2438044102208


In [31]:
#视图(view)和浅复制
#不同的数组对象分享同一个数据。视图方法创造一个新的数组对象指向同一数据。
c  = a.view()
c is a

False

In [32]:
c.base is a  # c is a view of the data owned by a

True

In [33]:
c.flags.owndata

False

In [34]:
c.shape = 2,6   # a's shape doesn't change
a.shape

(3, 4)

In [35]:
c[0,4] = 1234    # a's data changesa
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [36]:
#切片数组返回它的一个视图：
s = a[:,1:3]    # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10       # s[:] is a view of s. Note the difference between s=10 and s[:]=10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [37]:
#深复制
#这个方法完全复制数组和它的数据
d = a.copy()    # a new array object with new data is created
d is a

False

In [38]:
d.base is a   # d doesn't share anything with a

False

In [39]:
d[0,0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [ ]:
#函数和方法method总览
#这是个Numpy函数和方法分类排列目录。这些名字链接到Numpy示例,你可以看到这些函数起作用

#创建数组
#arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity,   
#linspace, logspace, mgrid, ogrid, ones, ones_like, r , zeros, zeros_like

#转化
#astype, atleast 1d, atleast 2d, atleast 3d, mat

#操作
#array split, column stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, item,   
#newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

#询问
#all, any, nonzero, where

#排序
#argmax, argmin, argsort, max, min, ptp, searchsorted, sort

#运算
#choose, compress, cumprod, cumsum, inner, fill, imag, prod, put, putmask, real, sum

#基本统计
#cov, mean, std, var

#基本线性代数
#cross, dot, outer, svd, vdot